helpwave/services

.build/service.Dockerfile
.dockerignore
Dockerfile.service
Makefile
README.md
services/emergency-room-svc/Makefile
services/user-svc/Makefile

feat: add Makefiles and fix docker builds

---

services/emergency-room-svc/api/v1.go
services/emergency-room-svc/main.go

Add create ER handler

---

.github/workflows/cicd.yaml

ci: apply correct indent

---

services/emergency-room-svc/api/v1.go
services/emergency-room-svc/main.go

feat(er-svc): add get handler

---

libs/hwgorm/pagination.go
libs/hwgorm/point.go
libs/hwutil/types.go
services/emergency-room-svc/api/v1.go
services/emergency-room-svc/main.go
services/emergency-room-svc/migrations/000001_init.down.sql
services/emergency-room-svc/migrations/000001_init.up.sql
services/emergency-room-svc/migrations/mocks.sql

feat(er-svc): add get-ers handler

---

.github/workflows/cicd.yaml
Dockerfile.service

Copy migrations into final image

---

libs/common/dapr.go
services/emergency-room-svc/main.go
services/user-svc/main.go

feat(common): abstract encoding of response

---

services/emergency-room-svc/api/v1.go
services/emergency-room-svc/main.go
services/emergency-room-svc/models/er.go

feat(er-svc): add update route

---

libs/common/grpc.go

chore(common): use log level Error instead of Warn for logging middleware

---

libs/common/grpc.go
services/user-svc/api/user-svc.pb.go
services/user-svc/api/user-svc.proto

feat(user-svc): limit orga name length

---

.github/workflows/buf.yaml

fix(ci): access violation

---

infrastructure/terraform/modules/hw-tf-module-cluster-resources/apisix.tf

feat(infra): expose task-svc via gRPC-web

---

.github/workflows/buf.yaml
gen/proto/services/auth_svc/v1/auth_svc.pb.go
gen/proto/services/auth_svc/v1/auth_svc_grpc.pb.go
services/emergency-room-svc/main.go
services/user-svc/main.go

`emergency-room-svc` and `user-svc` failed to build

fix: use correct protos

---

gen/go/proto/services/user_svc/v1/user_svc.pb.go
proto/services/emergency_room_svc/v1/emergency_room_svc.proto
proto/services/user_svc/v1/user_svc.proto

Just a commit with some unnecessary changes to trigger a publish on npm

ci: trigger publish

---

Makefile
README.md
dev/docker-compose.yaml
dev/init.sql

chore: getting started

---

libs/hwutil/arrays.go
services/task-svc/internal/task/task.go
services/task-svc/migrations/000001_init.up.sql
services/task-svc/migrations/000005_init.down.sql
services/task-svc/migrations/000005_init.up.sql

check and add task-svc functions

---

services/auth-svc/go.mod
services/task-svc/internal/room/models/models.go
services/task-svc/internal/room/room.go
services/task-svc/migrations/000007_init.down.sql
services/task-svc/migrations/000007_init.up.sql

closes https://github.com/helpwave/services/issues/147

feat(room): check and add methods for room-svc

---

Makefile

closes #186
1. Use windows
2. Use the make commands

make proto and migrate-up windows compatible

---

Makefile
README.md
migrate.sh

closes #189
Look at the README.md

Update README.md regarding migrations

---

docker-run-migrations.sh
infrastructure/README.md
libs/hwgorm/go.mod
libs/hwgorm/setup.go
services/emergency-room-svc/main.go
services/task-svc/main.go
services/user-svc/main.go

Mostly for proper database handling on fly.

chore: prefer but not require POSTGRES_DSN for database setup

---

.github/workflows/cicd.yaml
.github/workflows/fly-deploy.yaml

ci: fly deploy build local only

---

services/task-svc/internal/task-template/models/models.go
services/task-svc/internal/task-template/task_template.go

chore: remove duplicated models from task_template.go

---

services/task-svc/internal/task-template/task_template.go

fix: return TaskTemplate where warId is not set

---

.github/workflows/fly-deploy.yaml
Dockerfile.standalone
apisix/apisix.yaml
infrastructure/README.md
services/task-svc/fly.toml
services/user-svc/fly.toml

This pull request will fix some essential build issues using the remote builder on Fly.io. We are also switching to a new deployment strategy and tracking metrics of our services using Fly.

infra: fix remote-build on fly

---

.github/workflows/fly-deploy.yaml

Sorry for the review ping.
I will override this.
Greetings.
In the future, we should dry run the CI as much as possible.
I don't want these stupid errors anymore.

fix: sometimes ... i love CIs

---

services/task-svc/internal/task-template/task_template.go

fix: rename UpdateTaskTemplateSubTask

---

services/user-svc/fly.toml

infra: add release_command to user-svc

---

services/task-svc/internal/bed/models/models.go
services/task-svc/internal/patient/models/models.go
services/task-svc/internal/room/models/models.go
services/task-svc/internal/task-template/models/models.go
services/task-svc/internal/task/models/models.go
services/task-svc/internal/ward/models/models.go
services/user-svc/internal/organization/organization.go

fix(gorm): add explicit calls on uuid_generate_v4()

---

README.md
dev/docker-compose.yaml
dev/servers.json
libs/common/grpc.go

dx and doc improvements

---

services/user-svc/internal/organization/organization.go

fix OrganizationsByUser

---

services/emergency-room-svc/main.go
services/task-svc/internal/patient/patient.go
services/task-svc/internal/room/room.go
services/task-svc/internal/task/task.go
services/user-svc/internal/organization/organization.go

remove unnecessary warnings

---

migrate.sh

fix migrate.sh for windows

---

.github/workflows/buf.yaml
.github/workflows/cicd-go.yaml
.github/workflows/cicd-images.yaml
.github/workflows/cicd.yaml

ci: fix unauthed deploys

---

libs/decaying_lru/setup.go
services/task-svc/internal/patient/patient.go
services/task-svc/internal/tracking/tracking.go
services/task-svc/main.go

recent patients tracking

---

services/user-svc/internal/organization/organization.go
services/user-svc/internal/repositories/organisation_repository.go

add isInOrganization check for invites

---

libs/decaying_lru/cmd/example/main.go

fix: incorrect comment

---

libs/common/grpc.go

feat: accept all organizations when fake token is enabled

---

services/task-svc/internal/repositories/task_repository.go
services/task-svc/migrations/000017_creation_date_subtask.down.sql
services/task-svc/migrations/000017_creation_date_subtask.up.sql

feat: sort subtasks by creation date

---

README.md

feat: add additional information to README.md

---

services/impulse_svc/static/challenges.json

chore: add challenges.json file

---

services/impulse_svc/impulse_svc/settings.py

fix: csrf for admin

---

services/impulse_svc/impulse_svc/settings.py

try o fix csrf for admin i guess

---

services/impulse_svc/grpc_service/tests.py
services/impulse_svc/grpc_service/views.py

chore: clean up impulse-svc

---

gen/python/google/protobuf/timestamp_pb2.py
gen/python/proto/libs/events/v1/organization_events_pb2.py
gen/python/proto/libs/events/v1/user_events_pb2.py
gen/python/proto/services/auth_svc/v1/auth_svc_pb2.py
gen/python/proto/services/emergency_room_svc/v1/emergency_room_svc_pb2.py
gen/python/proto/services/impulse_svc/v1/impulse_svc_pb2.py
gen/python/proto/services/ory_svc/v1/ory_svc_pb2.py
gen/python/proto/services/task_svc/v1/bed_svc_pb2.py
gen/python/proto/services/task_svc/v1/patient_svc_pb2.py
gen/python/proto/services/task_svc/v1/room_svc_pb2.py
gen/python/proto/services/task_svc/v1/task_svc_pb2.py
gen/python/proto/services/task_svc/v1/task_template_svc_pb2.py
gen/python/proto/services/task_svc/v1/ward_svc_pb2.py
gen/python/proto/services/user_svc/v1/organization_svc_pb2.py
gen/python/proto/services/user_svc/v1/user_svc_pb2.py
services/impulse_svc/gen/google/protobuf/timestamp_pb2.py
services/impulse_svc/gen/proto/libs/events/v1/organization_events_pb2.py
services/impulse_svc/gen/proto/libs/events/v1/user_events_pb2.py
services/impulse_svc/gen/proto/services/auth_svc/v1/auth_svc_pb2.py
services/impulse_svc/gen/proto/services/emergency_room_svc/v1/emergency_room_svc_pb2.py
services/impulse_svc/gen/proto/services/impulse_svc/v1/impulse_svc_pb2.py
services/impulse_svc/gen/proto/services/ory_svc/v1/ory_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/bed_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/patient_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/room_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/task_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/task_template_svc_pb2.py
services/impulse_svc/gen/proto/services/task_svc/v1/ward_svc_pb2.py
services/impulse_svc/gen/proto/services/user_svc/v1/organization_svc_pb2.py
services/impulse_svc/gen/proto/services/user_svc/v1/user_svc_pb2.py

Looks like someone merged too early

run make proto

---

services/user-svc/internal/organization/organization.go

closes #459
```
INSERT INTO USERS VALUES ('f9d71ced-39a3-4eb4-9d1d-6f6b3a424ab9', 'max@bmn.dev', 'Max', 'Max Baumann');
INSERT INTO organizations VALUES ('3b25c6f5-4705-4074-9fc6-a50c28eba406', 'Some Org', 'asdasd', 'max@bmn.dev', NULL, false, 'f9d71ced-39a3-4eb4-9d1d-6f6b3a424ab9');
INSERT INTO memberships VALUES ('f2a687d8-a278-4f60-86f6-c4f0a4d44881', 'f9d71ced-39a3-4eb4-9d1d-6f6b3a424ab9', '3b25c6f5-4705-4074-9fc6-a50c28eba406', true);
INSERT INTO USERS VALUES ('7bb3ccfa-e8ec-4c1a-918e-d9ddc328ad63', 'max+other@bmn.dev', 'Max2', 'Max Baumann 2');
INSERT INTO memberships VALUES ('3047a3c3-1fef-485d-987a-d89de67915b1', '7bb3ccfa-e8ec-4c1a-918e-d9ddc328ad63', '3b25c6f5-4705-4074-9fc6-a50c28eba406', true);
INSERT INTO USERS VALUES ('73dca29f-b611-460b-887f-1472f8ca37b7', …
```

fix GetMembersByOrganization

---

services/user-svc/internal/organization/organization.go
services/user-svc/internal/repositories/organisation_repository.go

closes #375
```bash
$ grep -ir "organisation" . | wc -l
0
```

chore: organiZation

---

libs/hwgorm/logger.go
services/task-svc/internal/bed/bed.go
services/task-svc/internal/patient/patient.go
services/task-svc/internal/room/room.go
services/task-svc/internal/task-template/task_template.go
services/task-svc/internal/task/task.go
services/task-svc/internal/ward/ward.go
services/user-svc/internal/organization/organization.go
services/user-svc/internal/repositories/user_repository.go

chore: consistent log keys

---

apisix/apisix.yaml
apisix/apisix_config.yaml
apisix/fly.toml

We proxy gRPC directly for mobile

chore: proxy gRPC

---

.github/workflows/migrations.yaml

closes #470
Example of acceptable change being allowed: https://github.com/helpwave/services/actions/runs/6561691245/job/17821930251
Example of unacceptable change being rejected: https://github.com/helpwave/services/actions/runs/6561735521/job/17822079720

ci: use pg-fingerprint-action

---

.github/workflows/cicd.yaml
.github/workflows/fly-deploy.yaml

closes #479
this is untested, proceed with caution

cd: add version to fly

---

.github/dependabot.yaml

unfortunately we can't have nice things

---

README.md
apisix/Procfile.apisix
apisix/apisix.yaml
apisix/apisix_config.dev.yaml
dapr_run.yaml
devenv.nix
nix/devenv/scripts.nix

add APISIX to devenv up

---

services/task-svc/internal/repositories/patient_repository.go

extends getPatient with dischargedPatients

---

infrastructure/README.md
services/ory-svc/fly.toml
services/task-svc/fly.production.toml
services/task-svc/fly.staging.toml
services/user-svc/fly.production.toml
services/user-svc/fly.staging.toml

Closes #609
I hope that this change is temporary.
https://github.com/superfly/flyctl/pull/3174#issuecomment-1890087682

fix(fly): remove services with no ports

---

services/tasks-svc/internal/patient/aggregate/aggregate.go
services/tasks-svc/internal/patient/aggregate/aggregate_test.go
services/tasks-svc/internal/patient/models/patient.go

adds patient aggregate

---

services/tasks-svc/internal/patient/aggregate/aggregate.go
services/tasks-svc/internal/patient/aggregate/aggregate_test.go
services/tasks-svc/internal/patient/events/v1/events.go
services/tasks-svc/internal/patient/models/patient.go

adds patient events

---

services/tasks-svc/internal/task/aggregate/aggregate.go
services/tasks-svc/internal/task/models/task.go

removes NewTask and NewSubtask

---

.github/workflows/cicd.yaml

ci: actually run images ci

---

.github/workflows/buf.yaml
.github/workflows/ci-go-libs.yaml
.github/workflows/cicd-go.yaml
.github/workflows/cicd-images.yaml
.github/workflows/cicd.yaml
.github/workflows/hibernate-gke.yaml
.github/workflows/migrations.yaml
.github/workflows/publish-bufs.yaml

This is #657 without the postgres update

update github actions dependencies

---

.github/workflows/publish-bufs.yaml

ci: fix buf ratelimited

---

services/tasks-svc/internal/patient/aggregate/actions.go
services/tasks-svc/internal/patient/aggregate/aggregate.go
services/tasks-svc/internal/patient/aggregate/aggregate_test.go
services/tasks-svc/internal/patient/commands/v1/assign_bed.go
services/tasks-svc/internal/patient/commands/v1/create_patient.go
services/tasks-svc/internal/patient/commands/v1/discharge_patient.go
services/tasks-svc/internal/patient/commands/v1/readmit_patient.go
services/tasks-svc/internal/patient/commands/v1/unassign_bed.go
services/tasks-svc/internal/patient/commands/v1/update_patient.go
services/tasks-svc/internal/patient/events/v1/events.go
services/tasks-svc/internal/task/aggregate/actions.go
services/tasks-svc/internal/task/aggregate/aggregate_test.go
services/tasks-svc/internal/task/commands/v1/create_task.go
services/tasks-svc/internal/task/commands/v1/update_task.go
services/tasks-svc/internal/task/events/v1/events.go

adds patient commands

---

.gitignore
gen/dart/.gitignore
gen/dart/.pubignore

closes #698
I explicitly un-ignored `lib` here, I think there is a bug in the ignore detection (see my comment in #698)

fix: pubignore

---

README.md
dev/dapr_run.yaml
gen/go/proto/services/tasks_svc/v1/patient_svc.pb.go
libs/common/auth.go
libs/common/grpc.go
libs/common/setup.go
proto/services/tasks_svc/v1/patient_svc.proto
services/ory-svc/main.go
services/property-svc/main.go
services/task-svc/.env.example
services/task-svc/main.go
services/tasks-svc/go.mod
services/tasks-svc/internal/patient/api/grpc_test.go
services/tasks-svc/main.go
services/user-svc/main.go

**Meta**
* add tasks-svc to docker-compose
* remove outdated comment
**Issue**
* id of GetPatientRequest was not properly validated
**Testing**
* moved Setup to Options pattern
* add "fakeOnly" authentication setup
* add tests for fix
Future work: make `server()` reusable, move assert function

fix: validation error

---

libs/common/go.mod
libs/common/grpc.go
libs/common/test/grpc.go
libs/common/test/grpc_test.go
libs/hwutil/arrays.go
services/property-svc/go.mod
services/tasks-svc/internal/patient/api/grpc_test.go
services/tasks-svc/internal/task/api/grpc_test.go

- **refactor: create common_test module**
- **refactor: add user metadata to client in tests**
- **refactor: unified setup/teardown functions**

refactor: testing setup

---

.github/workflows/cicd.yaml
README.md
dev/docker-compose.yaml
images/dev-go/Dockerfile
images/dev-go/update-dev-tag.sh
lint.sh

feat: add local linter (also fixes build)

---

.github/workflows/migrations.yaml

chore(ci): migrate handle down to 0

---

services/tasks-svc/internal/patient/api/grpc.go
services/tasks-svc/internal/patient/api/grpc_test.go
services/tasks-svc/internal/patient/commands/v1/commands.go
services/tasks-svc/internal/patient/handlers/handlers.go
services/tasks-svc/internal/patient/queries/v1/queries.go
services/tasks-svc/main.go

add patient handlers registry

---

services/impulse_svc/fly.toml
services/task-svc/fly.production.toml
services/task-svc/fly.staging.toml
services/tasks-svc/fly.staging.toml
services/user-svc/fly.production.toml
services/user-svc/fly.staging.toml

fix: wait 30s before running migration

---

libs/common/auth.go
libs/common/dapr.go
libs/common/grpc.go
libs/common/otel.go
libs/hwauthz/spicedb/spicedb.go
libs/hwdb/setup.go
libs/hwes/aggregate.go
libs/hwes/event.go
libs/hwes/eventstoredb/aggregate_store.go
libs/hwes/eventstoredb/projections/custom/custom.go
libs/hwes/eventstoredb/replay.go
services/property-svc/internal/property-set/commands/v1/create_property_set.go
services/property-svc/internal/property-set/queries/v1/get_property_set_by_id.go
services/property-svc/internal/property-value/aggregate/actions.go
services/property-svc/internal/property-value/aggregate/aggregate.go
services/property-svc/internal/property-value/api/grpc.go

improve error handling

---

dev/docker-compose.yaml
libs/common/grpc.go
libs/common/setup.go
libs/hwes/eventstoredb/projections/custom/custom.go
libs/hwes/eventstoredb/projections/start.go
services/ory-svc/main.go
services/property-svc/cmd/service/main.go
services/property-svc/internal/property-view/api/grpc_test.go
services/property-svc/internal/property/projections/property_postgres_projection/property_postgres_projection.go
services/task-svc/main.go
services/tasks-svc/internal/patient/api/grpc_test.go
services/tasks-svc/internal/task/api/grpc_test.go
services/tasks-svc/main.go
services/user-svc/main.go

StartProjections

---

gen/go/services/property_svc/v1/property_svc.pb.go
gen/go/services/tasks_svc/v1/task_template_svc.pb.go
proto/services/property_svc/v1/property_svc.proto
proto/services/tasks_svc/v1/task_template_svc.proto
services/property-svc/stories/PropertyValueCRUD_test.go

closes #836 
There were only a few places where `validate` had to be added

Evaluate dive validator

---

gen/dart/.pubignore

dart: include libs

---

apisix/apisix_config.yaml
infrastructure/fly/jaeger.staging.toml
services/property-svc/fly.staging.toml
services/task-svc/fly.staging.toml
services/tasks-svc/fly.staging.toml
services/user-svc/fly.staging.toml

You can access Jaeger via the Fly Staging VPN
http://helpwave-staging-jaeger.internal:16686

chore: add jaeger

---

.github/workflows/publish-bufs.yaml
README.md
buf.yaml
gen/ts/package.json
proto/README.md
proto/services/tasks_svc/v1/bed_svc.proto

https://buf.build/helpwave/services

chore: push protos into Buf Schema Registry

---

libs/common/setup.go
libs/hwauthz/spicedb/migrate/migrate.go
libs/hwauthz/spicedb/spicedb_test.go
services/property-svc/stories/GetProperty_test.go

add AppCallbackHealthCheck_HealthCheck route to unauthed methods

---

libs/common/auth/auth.go
libs/common/auth/auth_test.go

feat: use go-validator with IDTokenClaims

---

.golangci.yaml
libs/common/hwgrpc/panic_interceptor_test.go
services/tasks-svc/internal/patient/aggregate/aggregate_test.go
services/tasks-svc/internal/patient/api/grpc_test.go
services/tasks-svc/internal/task/aggregate/aggregate_test.go
services/tasks-svc/internal/task/api/grpc_test.go
services/tasks-svc/stories/PatientCRUD_test.go
services/tasks-svc/stories/TaskCRUD_test.go

chore: enable goconst

---

.golangci.yaml
cmd/spice/spice.go
services/property-svc/internal/property/events/v1/events.go
services/tasks-svc/internal/task/events/v1/events.go

Re: #865
Adds tagliatelle linter

chore: tagliatelle
